inherit_from: ../.rubocop.yml

Metrics/LineLength:
  Enabled: false  
Metrics/BlockLength:
  Enabled: false  
Metrics/MethodLength:
  Enabled: false  
# expect to raise multi line
Style/MethodCalledOnDoEndBlock:  
  Enabled: false  